### ISSUE TITLE
Cuidado com suas keys

### ISSUE THREAD

**Issue by Alexbrazdasilva** [mayronH/reaction-time-v2#1]
https://github.com/mayronH/reaction-time-v2/blob/ad93f4111a2c632a9218cd02fbf0a7a1c31275e9/src/firebase/firebaseInit.ts#L6

**Comment by mayronH** [comment]
Vlw pela dica, como não tem cartão ou qualquer coisa minha relacionada na conta do firebase, subi o código sem medo. Vou atualizar para utilizar um .env de qualquer forma.
